export const OPERATORS = [
  {
    id: "mtn",
    name: "MTN",
    country: "Nigeria",
    color: "#FFCC00",
    dark: "#1a1a1a",
    prefix: ["0803", "0806", "0703", "0903", "0813", "0816"],
    share: 38,
    dcbCapDaily: 50000,
    revenueShare: 62,
  },
  {
    id: "airtel",
    name: "Airtel",
    country: "Nigeria",
    color: "#E40000",
    dark: "#ffffff",
    prefix: ["0802", "0808", "0708", "0902", "0812"],
    share: 27,
    dcbCapDaily: 45000,
    revenueShare: 60,
  },
  {
    id: "glo",
    name: "Glo",
    country: "Nigeria",
    color: "#00A651",
    dark: "#ffffff",
    prefix: ["0805", "0807", "0705", "0905", "0815"],
    share: 17,
    dcbCapDaily: 30000,
    revenueShare: 65,
  },
  {
    id: "9mobile",
    name: "9mobile",
    country: "Nigeria",
    color: "#8CC63F",
    dark: "#1a1a1a",
    prefix: ["0809", "0817", "0818", "0909"],
    share: 6,
    dcbCapDaily: 25000,
    revenueShare: 68,
  },
  {
    id: "safaricom",
    name: "Safaricom",
    country: "Kenya",
    color: "#59A845",
    dark: "#ffffff",
    prefix: ["0722", "0720", "0733", "0711"],
    share: 64,
    dcbCapDaily: 3000,
    revenueShare: 70,
  },
  {
    id: "vodacom",
    name: "Vodacom",
    country: "South Africa",
    color: "#E60000",
    dark: "#ffffff",
    prefix: ["082", "083", "084"],
    share: 42,
    dcbCapDaily: 1500,
    revenueShare: 58,
  },
];

export const ACTIVITY_CATALOG = [
  { key: "morning-walk", title: "Walk to Work / Market", category: "Move", description: "Brisk walking counts. 10-min bouts add up — park farther, walk the last bus stop.", pointsPerUnit: 12, unit: "min", caloriesPerUnit: 4.2, icon: "footprints", everyday: true },
  { key: "stair-climb", title: "Stair Climbing", category: "Move", description: "Skip the lift. 5 floors ≈ 2 min of vigorous cardio for heart health.", pointsPerUnit: 22, unit: "min", caloriesPerUnit: 9.5, icon: "trending-up", everyday: true },
  { key: "house-chores", title: "House Chores Sprint", category: "Move", description: "Sweeping, mopping, laundry — 30 min of chores burns ~120 kcal.", pointsPerUnit: 8, unit: "min", caloriesPerUnit: 3.8, icon: "home", everyday: true },
  { key: "market-carry", title: "Market Load Carry", category: "Strength", description: "Carrying shopping, water, or kids builds grip + core strength.", pointsPerUnit: 14, unit: "min", caloriesPerUnit: 5.1, icon: "shopping-bag", everyday: true },
  { key: "dance-break", title: "Dance Break", category: "Move", description: "3 songs of Afrobeats dancing = joyful zone-2 cardio + mood lift.", pointsPerUnit: 16, unit: "min", caloriesPerUnit: 6.4, icon: "music", everyday: true },
  { key: "farming-garden", title: "Farming / Gardening", category: "Strength", description: "Digging, weeding, fetching water — full-body functional fitness.", pointsPerUnit: 11, unit: "min", caloriesPerUnit: 4.8, icon: "sprout", everyday: true },
  { key: "cycle-commute", title: "Cycle / Okada Alternative", category: "Move", description: "Cycling short trips instead of riding. Huge cardio + savings.", pointsPerUnit: 15, unit: "min", caloriesPerUnit: 7.2, icon: "bike", everyday: true },
  { key: "stretch-snack", title: "Movement Snack", category: "Mobility", description: "2-min desk stretch: neck rolls, squats, wall push-ups. Every hour.", pointsPerUnit: 20, unit: "min", caloriesPerUnit: 2.6, icon: "timer", everyday: true },
  { key: "water", title: "Hydration", category: "Fuel", description: "Log water. In hot climates aim 2.5–3.5L/day. Every glass matters.", pointsPerUnit: 30, unit: "glass", caloriesPerUnit: 0, icon: "droplets", everyday: true },
  { key: "veg-plate", title: "Half-Plate Vegetables", category: "Fuel", description: "Fill half your plate with ugu, okra, cabbage, beans at one meal.", pointsPerUnit: 45, unit: "meal", caloriesPerUnit: 0, icon: "salad", everyday: true },
  { key: "sleep", title: "Sleep Window", category: "Rest", description: "7–9h in a dark room. Log hours slept — recovery is training.", pointsPerUnit: 18, unit: "hour", caloriesPerUnit: 0, icon: "moon", everyday: true },
  { key: "breathe", title: "Breathing Reset", category: "Mind", description: "Box breathing 4-4-4-4 for 3 min. Lowers stress + blood pressure.", pointsPerUnit: 35, unit: "session", caloriesPerUnit: 0, icon: "wind", everyday: true },
  { key: "no-soda", title: "Skip Sugary Drink", category: "Fuel", description: "Swap one soda/energy drink for water or zobo (no sugar).", pointsPerUnit: 50, unit: "swap", caloriesPerUnit: 0, icon: "ban", everyday: true },
  { key: "sunlight", title: "Morning Sunlight", category: "Mind", description: "10 min outdoor light before 10am. Anchors sleep + vitamin D.", pointsPerUnit: 25, unit: "session", caloriesPerUnit: 0, icon: "sun", everyday: true },
];

export const PLAN_CATALOG = [
  {
    code: "daily-flex",
    name: "Daily Flex",
    priceMinor: 10000,
    currency: "NGN",
    priceDisplay: "₦100/day",
    validityDays: 1,
    operator: "ALL",
    tagline: "Perfect starter — less than the cost of pure water sachet pack. Charged to airtime daily.",
    features: ["Full vitality score + logging", "Daily SMS health nudge", "1 active challenge", "Cancel anytime via *456*9#"],
    popular: false,
    airtimeCashbackPct: 5,
  },
  {
    code: "weekly-plus",
    name: "Weekly Plus",
    priceMinor: 50000,
    currency: "NGN",
    priceDisplay: "₦500/week",
    validityDays: 7,
    operator: "ALL",
    tagline: "Most popular for salary earners — auto-renews weekly, pause any week.",
    features: ["Everything in Daily Flex", "3 active challenges + family mode", "Weekly WhatsApp coach summary", "50MB bonus data on renewal", "Priority clinic finder"],
    popular: true,
    airtimeCashbackPct: 10,
  },
  {
    code: "monthly-max",
    name: "Monthly Max",
    priceMinor: 150000,
    currency: "NGN",
    priceDisplay: "₦1,500/month",
    validityDays: 30,
    operator: "ALL",
    tagline: "Best value — 50% cheaper than daily. Includes tele-consult discount.",
    features: ["Everything in Weekly Plus", "Unlimited challenges + squads", "1 free nurse tele-consult / month", "200MB bonus data + airtime cashback", "Annual health report"],
    popular: false,
    airtimeCashbackPct: 15,
  },
];

export const CHALLENGE_CATALOG = [
  { title: "6K Steps Daily Streak", description: "Hit 6,000 steps for 7 days straight. Built for commuters — walk the last stop.", category: "steps", targetPoints: 700, durationDays: 7, reward: "₦200 airtime + 100MB data", icon: "footprints", participants: 48210 },
  { title: "Stair Master Week", description: "Log 30 min of stair climbing in 7 days. Strong heart, strong legs.", category: "move", targetPoints: 500, durationDays: 7, reward: "₦150 airtime + badge", icon: "trending-up", participants: 12940 },
  { title: "Hydration Hero", description: "Drink 8 glasses daily for 5 days. Critical in harmattan & heat season.", category: "fuel", targetPoints: 600, durationDays: 5, reward: "₦100 airtime + streak shield", icon: "droplets", participants: 31022 },
  { title: "Soda-Free 14", description: "Skip sugary drinks for 14 days. Save ~₦7,000 and 4,200 kcal.", category: "fuel", targetPoints: 700, durationDays: 14, reward: "₦500 airtime + e-certificate", icon: "ban", participants: 18455 },
  { title: "Sleep Wealth", description: "Sleep 7+ hours for 10 nights. Recovery is the cheapest supplement.", category: "rest", targetPoints: 800, durationDays: 10, reward: "Free tele-consult slot", icon: "moon", participants: 9210 },
  { title: "Mindful Mornings", description: "3-min breathing reset every morning for 7 days. Lower stress daily.", category: "mind", targetPoints: 350, durationDays: 7, reward: "Calm+ premium week", icon: "wind", participants: 15670 },
];

export const TIPS_CATALOG = [
  { category: "Move", title: "Your commute is a gym membership", body: "A 20-minute brisk walk to the bus stop burns ~85 kcal and covers 40% of WHO's daily activity target. Do it twice daily and you exceed the 150 min/week guideline without ever entering a gym. Walk fast enough that you can talk but not sing.", readMins: 2 },
  { category: "Fuel", title: "The half-plate rule beats any diet", body: "Filipino, Nigerian or Kenyan plate — the rule travels: half vegetables (ugu, sukuma wiki, okra), quarter protein (beans, fish, eggs), quarter energy (rice, ugali, yam). Studies show this one habit cuts daily calories by 15–20% with zero tracking.", readMins: 3 },
  { category: "Rest", title: "Sleep before 11pm is worth double", body: "Growth hormone and deep-sleep cycles peak before 1am. Shifting bedtime from 1am to 10:30pm can improve morning blood pressure, memory and even skin — without sleeping longer. Dim lights, park your phone, keep the room cool.", readMins: 2 },
  { category: "Mind", title: "Box breathing for danfo stress", body: "Stuck in traffic? Try 4-4-4-4: inhale 4s, hold 4s, exhale 4s, hold 4s, repeat 4 rounds. Used by soldiers and surgeons, it drops heart rate within 3 minutes. Free, invisible, works everywhere.", readMins: 2 },
  { category: "Fuel", title: "Zobo > soda: save ₦500/day", body: "One 50cl soda = 13 cubes of sugar + ₦500. Homemade zobo with ginger and no added sugar costs ~₦80/glass. Swapping one daily soda saves ₦15,000/month — enough to pay for Monthly Max 10× over.", readMins: 3 },
  { category: "Move", title: "Chores are zone-2 cardio", body: "Mopping, sweeping and hand-washing clothes for 30 minutes keeps your heart at 55–65% max — the fat-burning zone. Put on music, move briskly, and log it. Housework counts toward your 150 minutes.", readMins: 2 },
];

export const OPERATOR_PREFIX_MAP: Record<string, string> = {
  "0803": "MTN", "0806": "MTN", "0703": "MTN", "0903": "MTN", "0813": "MTN", "0816": "MTN",
  "0802": "Airtel", "0808": "Airtel", "0708": "Airtel", "0902": "Airtel", "0812": "Airtel",
  "0805": "Glo", "0807": "Glo", "0705": "Glo", "0905": "Glo", "0815": "Glo",
  "0809": "9mobile", "0817": "9mobile", "0818": "9mobile", "0909": "9mobile",
};
